[package]
name = "ckb-sdk"
version = "2.4.0"
authors = ["Linfeng Qian <thewawar@gmail.com>", "Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "Rust SDK for CKB"
homepage = "https://github.com/nervosnetwork/ckb-sdk-rust"
repository = "https://github.com/nervosnetwork/ckb-sdk-rust"

[dependencies]
faster-hex = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
anyhow = "1.0.63"
bech32 = "0.8.1"
log = "0.4.6"
reqwest = { version = "0.11", features = ["json", "blocking"] }
secp256k1 = { version = "0.24", features = ["recovery"] }
tokio-util = { version = "0.6", features = ["codec"] }
tokio = { version = "1" }
bytes = "1"
futures = "0.3"
jsonrpc-core = "18"
parking_lot = "0.12"
lru = "0.7.1"
dashmap = "5.4"

ckb-types = "=0.106.0"
ckb-dao-utils = "=0.106.0"
ckb-traits = "=0.106.0"
ckb-jsonrpc-types = "=0.106.0"
ckb-hash = "=0.106.0"
ckb-resource = "=0.106.0"
ckb-crypto = { version = "=0.106.0", features = ["secp"] }
ckb-script = { version = "=0.106.0"}
bitflags = "1.3.2"
sha3 = "0.10.1"
enum-repr-derive = "0.2.0"

# for feature test
rand = { version = "0.7.3", optional = true }
ckb-mock-tx-types = { version = "0.106.0", optional = true }
ckb-chain-spec = { version = "=0.106.0", optional = true }

sparse-merkle-tree = "0.5.4"
lazy_static = "1.3.0"

[features]
default = []
test = []

[dev-dependencies]
clap = { version = "3.1.9", features = ["derive"] }
httpmock = "0.6"
async-global-executor = "=2.0.4"
hex = "0.4"
